FROM node:22-alpine AS build
WORKDIR /app
COPY frontend/package.json frontend/angular.json frontend/tsconfig.json ./
COPY frontend/src ./src
RUN npm install

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80

